apiVersion: v1
kind: Service
metadata:
  name: test-nginx
  namespace: default
spec:
  type: NodePort
  selector:
    app: test-nginx
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30001
