apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevirt
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/ulrikof/argocd-test
    targetRevision: main
    path: kubevirt
    kustomize: {}

  destination:
    server: https://kubernetes.default.svc
    namespace: kubevirt

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
